### ISSUE TITLE
示例命令执行时gpu不可用的问题

### ISSUE THREAD

**Issue by AIR-hl** [nju-websoft/muKG#12]
![X)IJQ NC%D(OZV}8S7378$X](https://user-images.githubusercontent.com/66808901/224679766-613a845d-3f52-485e-b1c9-7cd13d4c3c75.png)
![3RY19G80Y{BRON 6 XZ)DPF](https://user-images.githubusercontent.com/66808901/224679782-6c89c9e9-a7c7-4790-adf7-6a68320dab6c.png)
请问为什么按照示例命令执行，GPU状态可用，上面却输出的是 ea_models 的路径，device也变成 cpu 了

**Comment by luoxindi** [comment]
你好，在general_models.py文件的infer_model函数中，会导入进其他模型的进行初始化，使得某些模型会打印无关信息对您造成误解，稍后我会修改上传
