### ISSUE TITLE
EA任务中GCN_Align无法在GPU上训练

### ISSUE THREAD

**Issue by jxh4945777** [nju-websoft/muKG#3]
EA任务中GCN_Align无法在GPU上训练，请问如何修改，
我自己修改了之后，会存在显存逐渐OOM的现象；

**Comment by luoxindi** [comment]
感谢您的反馈，代码已经修改上传

**Comment by luoxindi** [comment]
> EA任务中GCN_Align无法在GPU上训练，请问如何修改， 我自己修改了之后，会存在显存逐渐OOM的现象；

感谢您的反馈，代码已经修改上传

**Comment by jxh4945777** [comment]
感谢，不过最近发现除了GCN_Align之外，torch版RDGCN等模型也存在无法在GPU上训练的问题，代码中examples对于GPU的支持存在部分缺失。

**Comment by luoxindi** [comment]
> 感谢，不过最近发现除了GCN_Align之外，torch版RDGCN等模型也存在无法在GPU上训练的问题，代码中examples对于GPU的支持存在部分缺失。

RDGCN模型已提供GPU支持，感谢反馈

**Comment by meteorlin** [comment]
您好！经测试，目前RDGCN在第一个epoch计算loss时还是会爆显存（16G的卡），位置在rdgcn.py:340，请问有什么方法可以避免OOM吗？或者说作者有没有计划公布预训练模型？

**Comment by luoxindi** [comment]
> 

你好，OOM是由于负样本设置过大造成的，可通过减少负样本数量来避免显存溢出，代码已更新上传

**Comment by luoxindi** [comment]
> 你好，OOM是由于负样本设置过大造成的，可通过减少负样本数量来避免显存溢出，代码已更新上传



> 您好！经测试，目前RDGCN在第一个epoch计算loss时还是会爆显存（16G的卡），位置在rdgcn.py:340，请问有什么方法可以避免OOM吗？或者说作者有没有计划公布预训练模型？

你好，OOM是由于负样本设置过大造成的，可通过减少负样本数量来避免显存溢出，代码已更新上传

**Comment by luoxindi** [comment]
> 您好！经测试，目前RDGCN在第一个epoch计算loss时还是会爆显存（16G的卡），位置在rdgcn.py:340，请问有什么方法可以避免OOM吗？或者说作者有没有计划公布预训练模型？

你好，OOM是由于负样本设置过大造成的，可通过减少负样本数量来避免显存溢出，代码已更新上传
