### ISSUE TITLE
main_args.py 文件在哪里？

### ISSUE THREAD

**Issue by Hianghua** [nju-websoft/muKG#6]
作者可以提供测试文件吗？ 我把提供的例子当成main_arg.py的时候 提示 没有 load_arg 函数，我试图找有这个函数的文件，但是没找到

**Comment by luoxindi** [comment]
> 

你好，load_args 函数在src/py目录下的args_handler.py文件中，需要在src/py路径下命令行执行main_arg.py文件

**Comment by Hianghua** [comment]
感谢回复！！
